FROM postgres:16-alpine

ENV POSTGRES_USER=root
ENV POSTGRES_PASSWORD=root
ENV POSTGRES_DB=postgres

# Exposer le port 5432 pour PostgreSQL
EXPOSE 5432

# Commande par défaut pour démarrer PostgreSQL
CMD ["postgres"]