services:
  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./tools/web/config.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www:delegated
    depends_on:
      - php

  php:
    image: php:8.2-fpm
    container_name: php
    volumes:
      - .:/var/www:delegated
    environment:
      networks: dev

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    networks:
      - dev

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - dev

volumes:
  db-data:
  redis-data:

networks:
  dev:
    driver: bridge
